DEBUG 2021-05-16 22:03:13.148 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-05-16 22:03:13.148 UTC: 	 Running on: Linux lxplus727.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-05-16 22:03:13.148 UTC: 	 Executing command: 'status'
DEBUG 2021-05-16 22:03:13.149 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/mmyllyma/.crab3
ERROR 2021-05-16 22:03:13.169 UTC: 	 Error: ./crab_step2_pi_100k is not a valid CRAB project directory.
ERROR 2021-05-16 22:03:13.169 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: ./crab_step2_pi_100k is not a valid CRAB project directory.
INFO 2021-05-16 22:03:13.173 UTC: 	 Log file is /afs/cern.ch/work/m/mmyllyma/singleParticleResponse/CMSSW_10_4_0/src/PFCalibration/PFChargedHadronAnalyzer/mmylly/crab.log
