DEBUG 2021-01-04 12:38:59.719 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-04 12:38:59.720 UTC: 	 Running on: Linux lxplus739.cern.ch 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-04 12:38:59.720 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-04 12:38:59.720 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/mmyllyma/.crab3
INFO 2021-01-04 12:38:59.721 UTC: 	 Will use CRAB configuration file crab_generate_pi_1M.py
DEBUG 2021-01-04 12:38:59.721 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-01-04 12:38:59.728 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2021-01-04 12:38:59.728 UTC: 	 Working area '/afs/cern.ch/work/m/mmyllyma/singleParticleResponse/CMSSW_10_4_0/src/PFCalibration/PFChargedHadronAnalyzer/mmylly/pi+/crab_generate_pi_1M' already exists 
Please change the requestName in the config file
ERROR 2021-01-04 12:38:59.728 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/mmyllyma/singleParticleResponse/CMSSW_10_4_0/src/PFCalibration/PFChargedHadronAnalyzer/mmylly/pi+/crab_generate_pi_1M' already exists 
Please change the requestName in the config file
INFO 2021-01-04 12:38:59.733 UTC: 	 Log file is /afs/cern.ch/work/m/mmyllyma/singleParticleResponse/CMSSW_10_4_0/src/PFCalibration/PFChargedHadronAnalyzer/mmylly/pi+/crab.log
DEBUG 2021-01-04 20:57:06.913 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-04 20:57:06.913 UTC: 	 Running on: Linux lxplus774.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-04 20:57:06.913 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-04 20:57:06.913 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/mmyllyma/.crab3
INFO 2021-01-04 20:57:06.915 UTC: 	 Will use CRAB configuration file crab_step2_pi_1M.py
DEBUG 2021-01-04 20:57:06.915 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-01-04 20:57:06.926 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-01-04 20:57:06.926 UTC: 	 Working area '/afs/cern.ch/work/m/mmyllyma/singleParticleResponse/CMSSW_10_4_0/src/PFCalibration/PFChargedHadronAnalyzer/mmylly/pi+/crab_step2_pi_1M' already exists 
Please change the requestName in the config file
ERROR 2021-01-04 20:57:06.926 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/mmyllyma/singleParticleResponse/CMSSW_10_4_0/src/PFCalibration/PFChargedHadronAnalyzer/mmylly/pi+/crab_step2_pi_1M' already exists 
Please change the requestName in the config file
INFO 2021-01-04 20:57:06.944 UTC: 	 Log file is /afs/cern.ch/work/m/mmyllyma/singleParticleResponse/CMSSW_10_4_0/src/PFCalibration/PFChargedHadronAnalyzer/mmylly/pi+/crab.log
